### ISSUE TITLE
Cannot update component [] while rendering a different component []

### ISSUE THREAD

**Issue by dalxds** [microapps/gatsby-plugin-react-i18next#8] opened 2020-06-22 16:05 UTC
Hello and thanks for all the work in open-sourcing this component!
I'm getting a warning from React and I need some help to resolve it.

The **error** is:
> Cannot update a component (`Landing`) while rendering a different component (`PageRenderer`). To locate the bad setState() call inside `PageRenderer`, follow the stack trace as described in https://fb.me/setstate-in-render

And the **stack trace**:
```
__stack_frame_overlay_proxy_console__ | @ | index.js:2177
-- | -- | --
  | r | @ | react_devtools_backend.js:6
  | printWarning | @ | react-dom.development.js:89
  | error | @ | react-dom.development.js:61
  | warnAboutRenderPhaseUpdatesInDEV | @ | react-dom.development.js:23242
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21166
  | dispatchAction | @ | react-dom.development.js:15661
  | boundReset | @ | useTranslation.js:70
  | (anonymous) | @ | i18next.js:149
  | emit | @ | i18next.js:148
  | done | @ | i18next.js:2003
  | (anonymous) | @ | i18next.js:2032
  | loadResources | @ | i18next.js:1937
  | setLng | @ | i18next.js:2031
  | changeLanguage | @ | i18next.js:2041
  | wrapPageElement | @ | wrapPageElement.js:100
  | (anonymous) | @ | api-runner-browser.js:35
  | ./.cache/api-runner-browser.js.exports.apiRunner | @ | api-runner-browser.js:22
  | render | @ | page-renderer.js:26
  | finishClassComponent | @ | react-dom.development.js:17161
  | updateClassComponent | @ | react-dom.development.js:17111
  | beginWork | @ | react-dom.development.js:18621
  | beginWork$1 | @ | react-dom.development.js:23180
  | performUnitOfWork | @ | react-dom.development.js:22155
  | workLoopSync | @ | react-dom.development.js:22131
  | performSyncWorkOnRoot | @ | react-dom.development.js:21757
  | (anonymous) | @ | react-dom.development.js:11090
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11040
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js:11085
  | flushSyncCallbackQueue | @ | react-dom.development.js:11073
  | scheduleUpdateOnFiber | @ | react-dom.development.js:21200
  | enqueueSetState | @ | react-dom.development.js:12640
  | ./node_modules/react/cjs/react.development.js.Component.setState | @ | react.development.js:471
  | (anonymous) | @ | index.js:103
  | requestAnimationFrame (async) |   |  
  | (anonymous) | @ | index.js:101
  | Promise.then (async) |   |  
  | (anonymous) | @ | index.js:99
  | (anonymous) | @ | history.js:100
  | navigate | @ | history.js:99
  | (anonymous) | @ | navigation.js:112
  | Promise.then (async) |   |  
  | navigate | @ | navigation.js:76
  | window.___navigate | @ | navigation.js:154
  | navigate | @ | index.js:279
  | changeLanguage | @ | useI18next.js:61
  | onClick | @ | index.js:20
  | callCallback | @ | react-dom.development.js:189
  | invokeGuardedCallbackDev | @ | react-dom.development.js:238
  | invokeGuardedCallback | @ | react-dom.development.js:293
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:307
  | executeDispatch | @ | react-dom.development.js:390
  | executeDispatchesInOrder | @ | react-dom.development.js:415
  | executeDispatchesAndRelease | @ | react-dom.development.js:3279
  | executeDispatchesAndReleaseTopLevel | @ | react-dom.development.js:3288
  | forEachAccumulated | @ | react-dom.development.js:3260
  | runEventsInBatch | @ | react-dom.development.js:3305
  | runExtractedPluginEventsInBatch | @ | react-dom.development.js:3515
  | handleTopLevel | @ | react-dom.development.js:3559
  | batchedEventUpdates$1 | @ | react-dom.development.js:21872
  | batchedEventUpdates | @ | react-dom.development.js:796
  | dispatchEventForLegacyPluginEventSystem | @ | react-dom.development.js:3569
  | attemptToDispatchEvent | @ | react-dom.development.js:4268
  | dispatchEvent | @ | react-dom.development.js:4190
  | unstable_runWithPriority | @ | scheduler.development.js:653
  | runWithPriority$1 | @ | react-dom.development.js:11040
  | discreteUpdates$1 | @ | react-dom.development.js:21888
  | discreteUpdates | @ | react-dom.development.js:807
  | dispatchDiscreteEvent | @ | react-dom.development.js:4169



```

**Related Issues:**
[https://github.com/facebook/react/issues/18178](https://github.com/facebook/react/issues/18178)
[https://github.com/i18next/react-i18next/issues/1124](https://github.com/i18next/react-i18next/issues/1124)

Let me know if there is any other Info that I could provide that it would help you.
Also, I'd be glad to assist in a pr, if I get some help.

Thanks!

**Comment by jimmyn** [comment] 2020-06-22 16:17
Hi, this warning does not affect functionality. As soon as you have more than 10 lines of translations it will disappear. I'm not sure how it could be fixed right now. PR's are welcome.

Duplicate of #5

**Closed by jimmyn** 2020-06-22 16:17 UTC
